name: checkstyle & reviewdog

on: [ push ]

jobs:
  build:
  
    runs-on: ubuntu-latest
  
    steps:
    
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1.0.3
    
      - name: Download checkstyle
        run: curl -L -s https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.43/checkstyle-8.43-all.jar > checkstyle.jar
        
      - name: Run checkstyle & reviewdog
        run: java -jar checkstyle.jar -c config/checkstyle/checkstyle.xml app/src/main/java/com/ianwhite/testapplication/libraryapp/ \
          | reviewdog -f=checkstyle -reporter="github-check"
